apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-mongo
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-mongo
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 65
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 65
#  - type: Object
#    object:
#      metricName: requests-per-second
#      target:
#        apiVersion: extensions/v1beta1
#        kind: Ingress
#        name: main-route
#      targetValue: 1k
